# syntax highlighting:
# - find strings (configurable start / stop / escapes)
# - find symbols (explicit list)
# - find identifiers (configurable glue)
# - sort identifiers (numbers, keywords, normal)
# - find function calls
# - string format (%d, {})

[rust]
extension = "rs"
strings-normal = [
    { start = '"', stop = '"', escape = ['n', 'r', '\', "\n"], multi-line = true, strfmt-braces = true },
    { start = "'", stop = "'", escape = ['n', 'r', '\'], single-char = true },
    { start = 'r#"', stop = '"#', escape = ['n', 'r', '\'], multi-line = true }
]

multi-line-comments = [
    { start = '/*', stop = '*/', escape = [], multi-line = true },
]

comment-prefix = ['//']

symbols = [
    '&&', '&', '..', '|', '-', '+', '/', '*',
    '::', ';', '=>', '->', '(', ')', '[', ']',
    '{', '}', '!', '%', '.', ',', '#', '+=',
    '-=', '/=', '*=', '|=', '^', '^=', '&=',
    '<', '>', ':', '=', '?'
]

number-glue = ['_', '.']
numbers = ['dec', 'hex', 'oct', 'bin']
keywords-strong = ['use', 'mod', 'const', 'mut', 'ref', 'true', 'false', 'break', 'continue', 'return']
keywords-basic = ['type', 'impl', 'struct', 'enum']
keywords-weak = ['self', 'let', 'static', 'for', 'while', 'if', 'match', 'fn']
call-syms = ['(', '!', '<']

[toml]
extension = "toml"
strings-normal = [
    { start = "'", stop = "'", escape = [] },
    { start = "'''", stop = "'''", escape = [], multi-line = true },
    { start = '"', stop = '"', escape = ['n', 'r', '\'] },
    { start = '"""', stop = '"""', escape = ['n', 'r', '\'], multi-line = true }
]

multi-line-comments = []
comment-prefix = ['#']

symbols = ['[', ']', '{', '}', '.', ',', ':', '=']

number-glue = ['.', 'e', 'E', '-']
numbers = ['dec', 'hex', 'oct', 'bin']
keywords-strong = ['true', 'false']
keywords-basic = []
keywords-weak = []
call-syms = [']']